package:
  name: lima-mycamera
  version: 0.0.0

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - git
    - cmake
    - {{ compiler('cxx') }}
    - python {{ python }}
    - sip 4.18*           #For the SIP generator
    - lima-core
  run:
    - python {{ python }}
    - sip 4.18*           #For the SIP module
    - lima-core

test:
  import:
    - Lima.MyCamera
  commands:
    - cmake --version
    - ctest --version
    - cpack --version

about:
  home: https://github.com/esrf-bliss/Lima
  license: GPL
  license_file: COPYING
  summary: a library for the unified control of 2D detectors
